### ISSUE TITLE
Show the reader if an item has been selected

### ISSUE THREAD

**Issue by michb** [contao/news-bundle#44] opened 2018-08-02 12:55 UTC
Please add the handling for the ModuleNewsReader into the ModuleNewsList, just like the ModuleEventList handles the request for ModuleEventReader.

Both listing modules ModuleNewsList and ModuleEventList do the same steps in the `generate` methode

1. show backend information
1. sortOutProtected
1. return '' if there are no archives left
1. call parent generate function

But the ModuleEventList also does this between step 3 and 4
https://github.com/contao/calendar-bundle/blob/f18b9130ba4d02ef0c189ed5fb16ef8d2922c8ec/src/Resources/contao/modules/ModuleEventlist.php#L75-L79
```
// Show the event reader if an item has been selected
if ($this->cal_readerModule > 0  && (isset($_GET['events']) || (\Config::get('useAutoItem') && isset($_GET['auto_item']))))
{
	return $this->getFrontendModule($this->cal_readerModule, $this->strColumn);
}
```

I see no reason why the ModuleNewsReader cannot also this step.
In my opinion this would improve consistency and makes it easier to great nice URLs.

**Comment by fritzmg** [comment] 2018-08-02 13:01
Duplicate of #39

**Closed as completed** 2018-08-02 13:38 UTC
Labels: duplicate
